name: pnpm install
description: pnpm install Composite Action

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - run: echo "::set-output name=dir::$(pnpm store path)"
      id: pnpm-cache-dir
      shell: bash
    - uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-
    - run: pnpm install
      shell: bash
